services:

  # MLflow Tracking Server
  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri /mlruns --artifacts-destination /mlruns
    volumes:
      - ./mlruns:/mlruns # Persistência para os dados de artefatos e modelos
    container_name: mlflow-tracking
    ports:
      - "5000:5000" # Expondo o MLflow na porta 5000

  # Aplicação FastAPI (consome modelos do MLflow)
  fastapi-application:
    build:
      context: .
      dockerfile: Dockerfile.Service
    image: fastapi-application:latest
    container_name: fastapi-application
    depends_on:
      - mlflow-tracking-server # Garantir que o MLflow esteja pronto antes de iniciar a FastAPI
    environment:
      TRACKING_URI: "http://mlflow-tracking-server:5000" # Configurar o URI do MLflow no container
      MODEL_NAME: "random_forest_v2"                       # Nome do modelo
      MODEL_VERSION: "1" 
    #volumes:
     # - ./mlruns:/mlruns 
    ports:
      - "5003:5003" # Porta onde a FastAPI estará acessível